CREATE TABLE conversations (
 id TEXT PRIMARY KEY, created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE leads (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conversation_id TEXT NOT NULL UNIQUE REFERENCES conversations(id),
 name TEXT, phone TEXT, email TEXT, service TEXT, project_date TEXT, location TEXT,
 budget TEXT, description TEXT, status TEXT NOT NULL DEFAULT 'New',
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE messages (
 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 conversation_id TEXT NOT NULL REFERENCES conversations(id),
 role TEXT NOT NULL CHECK(role IN ('user','assistant')),
 content TEXT NOT NULL, created_at TEXT NOT NULL
);
CREATE INDEX idx_messages_conversation ON messages(conversation_id,id);
CREATE INDEX idx_leads_created ON leads(created_at DESC);
